- name: Create volumes,vms and images pool
  become: yes
  become_user: "{{ ceph_username}}"
  shell: ceph osd pool create {{ item.name }} {{ item.pg }}
  with_items: "{{ openstack_pool }}"
  when: inventory_hostname == groups['monitor'][0]

- name: Init Pool
  become: yes
  become_user: "{{ ceph_username}}"
  shell: rbd pool init {{ item.name }}
  with_items: "{{ openstack_pool }}"
  when: inventory_hostname == groups['monitor'][0]

- name: Copy Ceph Configuration to controller
  become: yes
  become_user: "{{ceph_username}}"
  shell: "cat /etc/ceph/ceph.conf | ssh {{ hostvars[item]['ansible_hostname'] }} sudo tee /etc/ceph/ceph.conf"
  with_items: "{{groups['controller']}}"
  when: inventory_hostname == groups['monitor'][0]

- name: Copy Ceph Configuration to compute
  become: yes
  become_user: "{{ceph_username}}"
  shell: "cat /etc/ceph/ceph.conf | ssh {{ hostvars[item]['ansible_hostname'] }} sudo tee /etc/ceph/ceph.conf"
  with_items: "{{groups['compute']}}"
  when: inventory_hostname == groups['monitor'][0]

- name: Create user cinder
  become: yes
  become_user: "{{ceph_username}}"
  shell: ceph auth get-or-create client.cinder mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rx pool=images'
  when: inventory_hostname == groups['monitor'][0]

- name: Create user glance
  become: yes
  become_user: "{{ceph_username}}"
  shell: ceph auth get-or-create client.glance mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=images'
  when: inventory_hostname == groups['monitor'][0]

- name: Copy client.glance keyring to controller
  become: yes
  become_user: "{{ceph_username}}"
  shell: ceph auth get-or-create client.glance | ssh {{ hostvars[item]['ansible_hostname'] }} sudo tee /etc/ceph/ceph.client.glance.keyring
  with_items: "{{ groups['controller'] }}"
  when: inventory_hostname == groups['monitor'][0]

- name: Copy client.cinder keyring to controller
  become: yes
  become_user: "{{ceph_username}}"
  shell: ceph auth get-or-create client.cinder | ssh {{ hostvars[item]['ansible_hostname'] }} sudo tee /etc/ceph/ceph.client.cinder.keyring
  with_items: "{{ groups['controller'] }}"
  when: inventory_hostname == groups['monitor'][0]

- name: Copy client.glance keyring to compute
  become: yes
  become_user: "{{ceph_username}}"
  shell: ceph auth get-or-create client.glance | ssh {{ hostvars[item]['ansible_hostname'] }} sudo tee /etc/ceph/ceph.client.glance.keyring
  with_items: "{{ groups['compute'] }}"
  when: inventory_hostname == groups['monitor'][0]

- name: Copy client.cinder keyring to compute
  become: yes
  become_user: "{{ceph_username}}"
  shell: ceph auth get-or-create client.cinder | ssh {{ hostvars[item]['ansible_hostname'] }} sudo tee /etc/ceph/ceph.client.cinder.keyring
  with_items: "{{ groups['compute'] }}"
  when: inventory_hostname == groups['monitor'][0]

- name: copy key cinder controller
  become: yes
  become_user: "{{ceph_username}}"
  shell: ceph auth get-key client.cinder | ssh {{ hostvars[item]['ansible_hostname'] }} sudo tee /tmp/client.cinder.key
  with_items: "{{ groups['controller'] }}"
  when: inventory_hostname == groups['monitor'][0]

- name: copy key cinder compute
  become: yes
  become_user: "{{ceph_username}}"
  shell: ceph auth get-key client.cinder | ssh {{ hostvars[item]['ansible_hostname'] }} sudo tee /tmp/client.cinder.key
  with_items: "{{ groups['compute'] }}"
  when: inventory_hostname == groups['monitor'][0]
